In [567]:
import pandas as pd
import numpy as np

In [568]:
movies = pd.read_csv('dataset/maindataset.csv')

In [569]:
movies.head(1)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,crew,videos,directors,keywords
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"Action, Adventure, Animation, Comedy, Family",Po is gearing up to become the spiritual leade...,"Jack Black, Awkwafina, Bryan Cranston, Viola D...","Hans Zimmer, Leslee Feldman, Christopher Knigh...","JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHznz...",Mike Mitchell,"martial arts, kung fu, china, sequel, panda, a..."

In [570]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9184 entries, 0 to 9183
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             9184 non-null   int64
 1   backdrop_path  9072 non-null   object
 2   poster_path    9162 non-null   object
 3   title          9184 non-null   object
 4   release_date   9175 non-null   object
 5   runtime        9184 non-null   int64
 6   vote_average   9184 non-null   float64
 7   certification  7683 non-null   object
 8   genres         9164 non-null   object
 9   overview       9167 non-null   object
 10  casts          9149 non-null   object
 11  crew           9170 non-null   object
 12  videos         8651 non-null   object
 13  directors      9162 non-null   object
 14  keywords       8493 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 1.1+ MB

In [571]:
#Missing values
movies.isnull().sum()

id                  0
backdrop_path     112
poster_path        22
title               0
release_date        9
runtime             0
vote_average        0
certification    1501
genres             20
overview           17
casts              35
crew               14
videos            533
directors          22
keywords          691
dtype: int64

In [572]:
# Specify the subset of columns where you want to check for null values
columns_to_check = ['release_date', 'genres', 'overview', 'casts', 'directors', 'keywords']

# Drop rows with null values in the specified columns
movies.dropna(subset=columns_to_check, inplace=True)

In [573]:
movies.isnull().sum()

id                  0
backdrop_path      40
poster_path         2
title               0
release_date        0
runtime             0
vote_average        0
certification    1055
genres              0
overview            0
casts               0
crew                0
videos            324
directors           0
keywords            0
dtype: int64

In [574]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8464 entries, 0 to 9182
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             8464 non-null   int64
 1   backdrop_path  8424 non-null   object
 2   poster_path    8462 non-null   object
 3   title          8464 non-null   object
 4   release_date   8464 non-null   object
 5   runtime        8464 non-null   int64
 6   vote_average   8464 non-null   float64
 7   certification  7409 non-null   object
 8   genres         8464 non-null   object
 9   overview       8464 non-null   object
 10  casts          8464 non-null   object
 11  crew           8464 non-null   object
 12  videos         8140 non-null   object
 13  directors      8464 non-null   object
 14  keywords       8464 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 1.0+ MB

In [575]:
#check for duplicate 
movies.duplicated().sum()

1975

In [576]:

movies.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9178    False
9179     True
9180     True
9181     True
9182    False
Length: 8464, dtype: bool

In [577]:
movies.drop_duplicates(inplace=True)

In [578]:
movies.duplicated().sum()

0

In [579]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6489 entries, 0 to 9182
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             6489 non-null   int64
 1   backdrop_path  6458 non-null   object
 2   poster_path    6488 non-null   object
 3   title          6489 non-null   object
 4   release_date   6489 non-null   object
 5   runtime        6489 non-null   int64
 6   vote_average   6489 non-null   float64
 7   certification  5703 non-null   object
 8   genres         6489 non-null   object
 9   overview       6489 non-null   object
 10  casts          6489 non-null   object
 11  crew           6489 non-null   object
 12  videos         6233 non-null   object
 13  directors      6489 non-null   object
 14  keywords       6489 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 811.1+ KB

In [580]:
movies.head(1)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,crew,videos,directors,keywords
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"Action, Adventure, Animation, Comedy, Family",Po is gearing up to become the spiritual leade...,"Jack Black, Awkwafina, Bryan Cranston, Viola D...","Hans Zimmer, Leslee Feldman, Christopher Knigh...","JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHznz...",Mike Mitchell,"martial arts, kung fu, china, sequel, panda, a..."

In [581]:
movies.iloc[0].genres

'Action, Adventure, Animation, Comedy, Family'

In [582]:
def process_genres(genres_str):
    # Split the string by comma and strip whitespace
    genres_list = genres_str.split(',')
    return genres_list

# Apply the function to the 'genres' column
movies['genres'] = movies['genres'].apply(lambda x: process_genres(x) if isinstance(x, str) else [])

In [583]:
movies.iloc[0].genres

['Action', ' Adventure', ' Animation', ' Comedy', ' Family']

In [584]:
movies.head(1)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,crew,videos,directors,keywords
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Fam...",Po is gearing up to become the spiritual leade...,"Jack Black, Awkwafina, Bryan Cranston, Viola D...","Hans Zimmer, Leslee Feldman, Christopher Knigh...","JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHznz...",Mike Mitchell,"martial arts, kung fu, china, sequel, panda, a..."

In [585]:
def process_casts(casts_str):
    # Split the string by comma and strip whitespace
    casts_list = casts_str.split(',')
    # Take the first four members if available, otherwise return an empty list
    first_four_casts = casts_list[:4]
    # Strip whitespace from each cast member's name
    first_four_casts = [cast.strip() for cast in first_four_casts]
    return first_four_casts

# Apply the function to the 'casts' column
movies['casts'] = movies['casts'].apply(lambda x: process_casts(x) if isinstance(x, str) else [])

In [586]:
movies.iloc[0].casts

['Jack Black', 'Awkwafina', 'Bryan Cranston', 'Viola Davis']

In [587]:
movies.drop('crew', axis=1, inplace=True)

In [588]:
movies.head(1)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Fam...",Po is gearing up to become the spiritual leade...,"[Jack Black, Awkwafina, Bryan Cranston, Viola ...","JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHznz...",Mike Mitchell,"martial arts, kung fu, china, sequel, panda, a..."

In [589]:
movies.iloc[0].keywords

'martial arts, kung fu, china, sequel, panda, anthropomorphism, angry, approving, callous'

In [590]:
movies.head(1)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Fam...",Po is gearing up to become the spiritual leade...,"[Jack Black, Awkwafina, Bryan Cranston, Viola ...","JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHznz...",Mike Mitchell,"martial arts, kung fu, china, sequel, panda, a..."

In [591]:
# Apply the function to the entire 'keywords' column
movies['keywords'] = movies['keywords'].apply(lambda x: x.split(', '))
movies['directors'] = movies['directors'].apply(lambda x: x.split(', '))
# Check for NaN values in the 'videos' column
nan_indices = movies['videos'].isnull()

# Apply splitting operation only to non-null values
movies.loc[~nan_indices, 'videos'] = movies.loc[~nan_indices, 'videos'].apply(lambda x: x.split(', '))

In [592]:
movies.head(3)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Fam...",Po is gearing up to become the spiritual leade...,"[Jack Black, Awkwafina, Bryan Cranston, Viola ...","[JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHzn...",[Mike Mitchell],"[martial arts, kung fu, china, sequel, panda, ..."
1,634492,/zAepSrO99owYwQqi0QG2AS0dHXw.jpg,/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg,Madame Web,14-02-2024,116,5.6,PG-13,"[Action, Fantasy]","Forced to confront revelations about her past,...","[Dakota Johnson, Sydney Sweeney, Isabela Merce...","[ZTycQKub30c, C0_VQWz3b6U, XBAVUzVmp0Y, xpkF2d...",[S.J. Clarkson],"[new york city, superhero, spider, based on co..."
2,763215,/deLWkOLZmBNkm8p16igfapQyqeq.jpg,/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg,Damsel,08-03-2024,110,7.2,PG-13,"[Mystery, Fantasy, Action, Adventure, Scie...",A young womans marriage to a charming prince t...,"[Millie Bobby Brown, Ray Winstone, Angela Bass...","[5fv9UdRC8eg, iM150ZWovZM, 9eN_AGX8GXk]",[Juan Carlos Fresnadillo],"[princess, fire, chase, kingdom, sword, mounta..."

In [593]:
def collapse(obj):
    l = []
    for i in obj:
        l.append(i.replace(" ",""))
    return l

In [594]:
movies['casts'] = movies['casts'].apply(collapse)
movies['directors'] = movies['directors'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [595]:
movies.head(1)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Family]",Po is gearing up to become the spiritual leade...,"[JackBlack, Awkwafina, BryanCranston, ViolaDavis]","[JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHzn...",[MikeMitchell],"[martialarts, kungfu, china, sequel, panda, an..."

In [596]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [597]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['casts']+movies['directors']

In [598]:
movies.head(2)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords,tags
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Family]","[Po, is, gearing, up, to, become, the, spiritu...","[JackBlack, Awkwafina, BryanCranston, ViolaDavis]","[JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHzn...",[MikeMitchell],"[martialarts, kungfu, china, sequel, panda, an...","[Po, is, gearing, up, to, become, the, spiritu..."
1,634492,/zAepSrO99owYwQqi0QG2AS0dHXw.jpg,/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg,Madame Web,14-02-2024,116,5.6,PG-13,"[Action, Fantasy]","[Forced, to, confront, revelations, about, her...","[DakotaJohnson, SydneySweeney, IsabelaMerced, ...","[ZTycQKub30c, C0_VQWz3b6U, XBAVUzVmp0Y, xpkF2d...",[S.J.Clarkson],"[newyorkcity, superhero, spider, basedoncomic,...","[Forced, to, confront, revelations, about, her..."

In [599]:
movies.iloc[0].tags

['Po',
 'is',
 'gearing',
 'up',
 'to',
 'become',
 'the',
 'spiritual',
 'leader',
 'of',
 'his',
 'Valley',
 'of',
 'Peace,',
 'but',
 'also',
 'needs',
 'someone',
 'to',
 'take',
 'his',
 'place',
 'as',
 'Dragon',
 'Warrior.',
 'As',
 'such,',
 'he',
 'will',
 'train',
 'a',
 'new',
 'kung',
 'fu',
 'practitioner',
 'for',
 'the',
 'spot',
 'and',
 'will',
 'encounter',
 'a',
 'villain',
 'called',
 'the',
 'Chameleon',
 'who',
 'conjures',
 'villains',
 'from',
 'the',
 'past.',
 'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Family',
 'martialarts',
 'kungfu',
 'china',
 'sequel',
 'panda',
 'anthropomorphism',
 'angry',
 'approving',
 'callous',
 'JackBlack',
 'Awkwafina',
 'BryanCranston',
 'ViolaDavis',
 'MikeMitchell']

In [600]:
new = movies

In [601]:
new.head(2)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords,tags
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Family]","[Po, is, gearing, up, to, become, the, spiritu...","[JackBlack, Awkwafina, BryanCranston, ViolaDavis]","[JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHzn...",[MikeMitchell],"[martialarts, kungfu, china, sequel, panda, an...","[Po, is, gearing, up, to, become, the, spiritu..."
1,634492,/zAepSrO99owYwQqi0QG2AS0dHXw.jpg,/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg,Madame Web,14-02-2024,116,5.6,PG-13,"[Action, Fantasy]","[Forced, to, confront, revelations, about, her...","[DakotaJohnson, SydneySweeney, IsabelaMerced, ...","[ZTycQKub30c, C0_VQWz3b6U, XBAVUzVmp0Y, xpkF2d...",[S.J.Clarkson],"[newyorkcity, superhero, spider, basedoncomic,...","[Forced, to, confront, revelations, about, her..."

In [602]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))

In [603]:
new.head(2)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords,tags
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Family]","[Po, is, gearing, up, to, become, the, spiritu...","[JackBlack, Awkwafina, BryanCranston, ViolaDavis]","[JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHzn...",[MikeMitchell],"[martialarts, kungfu, china, sequel, panda, an...",Po is gearing up to become the spiritual leade...
1,634492,/zAepSrO99owYwQqi0QG2AS0dHXw.jpg,/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg,Madame Web,14-02-2024,116,5.6,PG-13,"[Action, Fantasy]","[Forced, to, confront, revelations, about, her...","[DakotaJohnson, SydneySweeney, IsabelaMerced, ...","[ZTycQKub30c, C0_VQWz3b6U, XBAVUzVmp0Y, xpkF2d...",[S.J.Clarkson],"[newyorkcity, superhero, spider, basedoncomic,...","Forced to confront revelations about her past,..."

In [604]:
new['tags'] = new['tags'].apply(lambda x:x.lower())

In [605]:
new.head(2)

,id,backdrop_path,poster_path,title,release_date,runtime,vote_average,certification,genres,overview,casts,videos,directors,keywords,tags
0,1011985,/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg,/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg,Kung Fu Panda 4,02-03-2024,94,6.9,PG,"[Action, Adventure, Animation, Comedy, Family]","[Po, is, gearing, up, to, become, the, spiritu...","[JackBlack, Awkwafina, BryanCranston, ViolaDavis]","[JmF0LmnkkO4, F9DvXKOAHmc, j8o0DeI_pDY, 69yHzn...",[MikeMitchell],"[martialarts, kungfu, china, sequel, panda, an...",po is gearing up to become the spiritual leade...
1,634492,/zAepSrO99owYwQqi0QG2AS0dHXw.jpg,/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg,Madame Web,14-02-2024,116,5.6,PG-13,"[Action, Fantasy]","[Forced, to, confront, revelations, about, her...","[DakotaJohnson, SydneySweeney, IsabelaMerced, ...","[ZTycQKub30c, C0_VQWz3b6U, XBAVUzVmp0Y, xpkF2d...",[S.J.Clarkson],"[newyorkcity, superhero, spider, basedoncomic,...","forced to confront revelations about her past,..."

In [606]:
import nltk
from nltk.stem.porter import PorterStemmer

In [607]:
ps = PorterStemmer()

In [608]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [609]:
new['tags'] = new['tags'].apply(stem)

In [610]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6489 entries, 0 to 9182
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             6489 non-null   int64
 1   backdrop_path  6458 non-null   object
 2   poster_path    6488 non-null   object
 3   title          6489 non-null   object
 4   release_date   6489 non-null   object
 5   runtime        6489 non-null   int64
 6   vote_average   6489 non-null   float64
 7   certification  5703 non-null   object
 8   genres         6489 non-null   object
 9   overview       6489 non-null   object
 10  casts          6489 non-null   object
 11  videos         6233 non-null   object
 12  directors      6489 non-null   object
 13  keywords       6489 non-null   object
 14  tags           6489 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 811.1+ KB

In [611]:
import os
import pandas as pd

# Assuming you have DataFrame `new` already created

# Define the path to your dataset folder
dataset_folder = 'dataset'

# Create the dataset folder if it doesn't exist
if not os.path.exists(dataset_folder):
    os.makedirs(dataset_folder)

# Define the file path for saving the CSV
csv_filename = os.path.join(dataset_folder, 'new_data.csv')

# Check if the file already exists
if not os.path.exists(csv_filename):
    # Save the DataFrame to CSV
    new.to_csv(csv_filename, index=False)
    print(f"DataFrame saved to {csv_filename}")
else:
    print(f"The file {csv_filename} already exists. Data was not overwritten.")

The file dataset\new_data.csv already exists. Data was not overwritten.

In [612]:
#countvectorization
from sklearn.feature_extraction.text import CountVectorizer

In [613]:
cv = CountVectorizer(max_features = 5000, stop_words='english')

In [614]:
vector = cv.fit_transform(new['tags']).toarray()

In [615]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [616]:
from sklearn.metrics.pairwise import cosine_similarity

In [617]:
similarity = cosine_similarity(vector)

In [618]:
similarity

array([[1.        , 0.05372153, 0.11268723, ..., 0.02686077, 0.        ,
        0.19278508],
       [0.05372153, 1.        , 0.12712835, ..., 0.        , 0.        ,
        0.02718636],
       [0.11268723, 0.12712835, 1.        , ..., 0.03178209, 0.        ,
        0.05702659],
       ...,
       [0.02686077, 0.        , 0.03178209, ..., 1.        , 0.        ,
        0.08155909],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.04508348],
       [0.19278508, 0.02718636, 0.05702659, ..., 0.08155909, 0.04508348,
        1.        ]])

In [619]:
#recommend
def recommend(movie):
    # Convert the search query to lowercase
    movie = movie.lower()
    
    # Find the index of the movie in the DataFrame
    index = new[new['title'].str.lower() == movie].index[0]
    
    # Sort distances based on similarity
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
    
    # Print the titles of the top 5 similar movies
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [620]:
sorted(list(enumerate(similarity[0])), reverse=True,key = lambda x:x[1])

[(0, 1.0000000000000002),
 (61, 0.48498974603948153),
 (64, 0.47619047619047633),
 (41, 0.4330127018922194),
 (1109, 0.34646743359179155),
 (2037, 0.3367175148507369),
 (5190, 0.3306500356330541),
 (338, 0.32977508813069667),
 (2060, 0.32665262900407427),
 (1531, 0.31610431187743987),
 (235, 0.3120938919661797),
 (3038, 0.3086066999241839),
 (718, 0.3048506975105313),
 (250, 0.30440777365910465),
 (415, 0.30037570459305535),
 (396, 0.30004959907448947),
 (606, 0.30004959907448947),
 (3293, 0.2993924754260479),
 (3448, 0.29649972666444047),
 (4976, 0.2963477923850999),
 (5868, 0.29576024087563857),
 (562, 0.2939481756261077),
 (224, 0.2925969387941234),
 (4001, 0.28953301207179316),
 (5142, 0.28953301207179316),
 (66, 0.2895330120717931),
 (4012, 0.2869022920265156),
 (5083, 0.28368325730679006),
 (2770, 0.2836543144655877),
 (506, 0.28319693016191544),
 (1648, 0.2817180849095055),
 (1649, 0.27713699773684664),
 (2846, 0.27625462776753074),
 (2963, 0.2760262237369417),
 (4336, 0.27553753720954327),
 (1612, 0.27277236279499045),
 (237, 0.2721655269759086),
 (964, 0.2708976164365387),
 (6, 0.2704813730373557),
 (1847, 0.2700894819638062),
 (1678, 0.26837252006084666),
 (11, 0.2672612419124244),
 (5374, 0.2672612419124244),
 (3245, 0.26569371377681855),
 (1121, 0.2631806779839076),
 (1916, 0.2631806779839076),
 (5661, 0.2631806779839076),
 (4968, 0.26186146828319085),
 (3192, 0.26082026547865056),
 (5352, 0.2592814894208657),
 (3969, 0.25896619868911863),
 (3890, 0.2588414429342565),
 (5988, 0.2588414429342564),
 (4212, 0.25788071477756375),
 (2763, 0.25717224993681986),
 (1908, 0.2567762955065478),
 (52, 0.2558831578595795),
 (3666, 0.2558831578595795),
 (3113, 0.25559931622162385),
 (4946, 0.25475508554262666),
 (3384, 0.2545875386086578),
 (427, 0.25434234203957845),
 (4303, 0.25434234203957845),
 (4711, 0.25434234203957845),
 (2769, 0.2530240384255299),
 (3619, 0.2530240384255299),
 (301, 0.25197631533948484),
 (543, 0.25197631533948484),
 (950, 0.25197631533948484),
 (2855, 0.25197631533948484),
 (2964, 0.25197631533948484),
 (6356, 0.25197631533948484),
 (2137, 0.2519763153394848),
 (2499, 0.25145944030220063),
 (1036, 0.24967511357294372),
 (6479, 0.2496751135729437),
 (1783, 0.247797313891676),
 (2871, 0.24743582965269678),
 (2719, 0.24743582965269675),
 (1747, 0.2470831055537004),
 (1754, 0.24688535993934707),
 (5332, 0.24688535993934707),
 (3390, 0.2454951265154914),
 (382, 0.24525573579398635),
 (1230, 0.24525573579398635),
 (5582, 0.24525573579398635),
 (599, 0.24525573579398632),
 (2948, 0.24498947175305574),
 (2377, 0.24459979523511424),
 (3403, 0.24459979523511424),
 (2950, 0.24325638628366394),
 (2313, 0.24325638628366392),
 (3761, 0.24313226954193234),
 (1760, 0.24263079303098484),
 (1992, 0.242476692797573),
 (55, 0.24209101306752098),
 (844, 0.24209101306752098),
 (4282, 0.24209101306752098),
 (3658, 0.24209101306752095),
 (5503, 0.24171942265191476),
 (3792, 0.241522945769824),
 (1447, 0.24152294576982397),
 (4877, 0.24148722544931955),
 (2605, 0.24098134635593996),
 (3129, 0.24098134635593993),
 (4369, 0.24017943649073573),
 (4734, 0.24003967925959163),
 (2752, 0.23904572186687872),
 (4209, 0.23855936180684892),
 (2355, 0.23816525581123338),
 (1275, 0.23809523809523814),
 (257, 0.23756554836659946),
 (2678, 0.23711790231526927),
 (1260, 0.2357022603955159),
 (3710, 0.2357022603955159),
 (276, 0.23570226039551587),
 (2487, 0.23570226039551587),
 (3523, 0.23570226039551587),
 (3894, 0.23570226039551587),
 (2661, 0.23537827088100213),
 (4253, 0.23515854050088617),
 (5088, 0.23328473740792174),
 (1626, 0.23328473740792172),
 (2689, 0.23328473740792172),
 (4588, 0.23328473740792172),
 (4852, 0.23328473740792172),
 (513, 0.23314714686961358),
 (2494, 0.23314714686961355),
 (591, 0.23162640965743445),
 (3047, 0.23145502494313788),
 (1006, 0.23145502494313785),
 (1594, 0.23145502494313785),
 (4365, 0.23145502494313785),
 (1615, 0.23028309323591917),
 (1897, 0.23028309323591914),
 (518, 0.23002185311411807),
 (166, 0.23002185311411805),
 (5857, 0.23002185311411805),
 (1993, 0.22922730202450112),
 (2768, 0.2292273020245011),
 (3230, 0.2292273020245011),
 (4758, 0.2292273020245011),
 (3425, 0.22886885410853175),
 (5413, 0.2279211529192759),
 (5187, 0.22792115291927584),
 (332, 0.22750787759664504),
 (668, 0.227507877596645),
 (1780, 0.22712838128974894),
 (5453, 0.22712838128974894),
 (91, 0.22645540682891918),
 (2804, 0.22568628174911476),
 (711, 0.2253744679276044),
 (760, 0.2253744679276044),
 (4184, 0.2253744679276044),
 (5674, 0.2253744679276044),
 (3112, 0.2252817784447915),
 (3362, 0.2252817784447915),
 (3651, 0.2252817784447915),
 (2456, 0.22522130823072545),
 (4981, 0.22522130823072545),
 (5204, 0.22522130823072542),
 (542, 0.22507456830317185),
 (169, 0.22481775781115415),
 (4487, 0.22481775781115415),
 (3628, 0.22481775781115412),
 (4596, 0.22454435656953595),
 (1394, 0.22454435656953592),
 (6327, 0.22454435656953592),
 (1971, 0.22287124708010464),
 (2930, 0.22281245492773058),
 (2396, 0.22271770159368703),
 (3086, 0.222717701593687),
 (236, 0.22237479499833035),
 (2437, 0.22237479499833035),
 (3319, 0.22237479499833035),
 (2370, 0.22170959818947733),
 (2514, 0.22170959818947733),
 (317, 0.2217095981894773),
 (792, 0.2217095981894773),
 (3584, 0.2217095981894773),
 (114, 0.22170959818947727),
 (400, 0.22169722565685293),
 (2101, 0.22097443601483469),
 (2395, 0.22047927592204924),
 (745, 0.2204333570887027),
 (2464, 0.22018090929275003),
 (1218, 0.22018090929275),
 (347, 0.21957751641342),
 (431, 0.21912524504463884),
 (3006, 0.21912524504463882),
 (5336, 0.21912524504463882),
 (5970, 0.21886638465297903),
 (4230, 0.218866384652979),
 (3098, 0.21870444131992658),
 (402, 0.21821789023599242),
 (6257, 0.21821789023599242),
 (6478, 0.21821789023599242),
 (4138, 0.2182178902359924),
 (6453, 0.2182178902359924),
 (321, 0.21821789023599236),
 (1733, 0.21821789023599236),
 (1746, 0.21821789023599236),
 (2684, 0.21821789023599236),
 (3212, 0.21821789023599236),
 (4724, 0.21757512627648798),
 (179, 0.21732171441573994),
 (4989, 0.2171129824263099),
 (2916, 0.21688321172034594),
 (5755, 0.21688321172034594),
 (677, 0.21688321172034591),
 (565, 0.21671809314923096),
 (2480, 0.21671809314923096),
 (4542, 0.21606790785072144),
 (1130, 0.2160679078507214),
 (2740, 0.2160246899469287),
 (3979, 0.21602468994692867),
 (3982, 0.21602468994692867),
 (4548, 0.21602468994692867),
 (122, 0.21556199545914564),
 (464, 0.21524880100025257),
 (563, 0.2150597223603682),
 (107, 0.21488612374010144),
 (1122, 0.21488612374010144),
 (3262, 0.2148861237401014),
 (4281, 0.2148861237401014),
 (783, 0.2142857142857143),
 (448, 0.21398024625545647),
 (2434, 0.21398024625545647),
 (2588, 0.21398024625545647),
 (5561, 0.21398024625545647),
 (2147, 0.21384434262392826),
 (1804, 0.2138089935299395),
 (1018, 0.21380899352993948),
 (860, 0.21262959098900594),
 (588, 0.2123976976214366),
 (672, 0.2123976976214366),
 (5802, 0.2123976976214366),
 (721, 0.21239769762143657),
 (3588, 0.21239769762143657),
 (187, 0.21216710619787638),
 (4820, 0.21216710619787638),
 (6477, 0.21216710619787638),
 (189, 0.2119519516996487),
 (1277, 0.2119519516996487),
 (2781, 0.2119519516996487),
 (3627, 0.2119519516996487),
 (6106, 0.21195195169964867),
 (1605, 0.21182963643408087),
 (2384, 0.21182963643408087),
 (3839, 0.21182963643408087),
 (5131, 0.21182963643408087),
 (5714, 0.21182963643408087),
 (690, 0.21182963643408084),
 (1599, 0.21182963643408084),
 (4756, 0.2117793624007553),
 (1854, 0.21177936240075526),
 (1990, 0.21170244960998524),
 (4051, 0.2114450158055155),
 (4421, 0.210528725646512),
 (4307, 0.20935894733965596),
 (4945, 0.20935894733965593),
 (1266, 0.20892772350933625),
 (5086, 0.20892772350933625),
 (5813, 0.20865621238292043),
 (746, 0.20832579853764444),
 (3668, 0.2083257985376444),
 (388, 0.20806259464411977),
 (1101, 0.20806259464411975),
 (1907, 0.20786985482077452),
 (4122, 0.20786985482077452),
 (5218, 0.20786985482077452),
 (6006, 0.20786985482077452),
 (1774, 0.20736269979903807),
 (6311, 0.20736269979903807),
 (6346, 0.20701966780270628),
 (243, 0.20701966780270625),
 (3465, 0.20701966780270625),
 (4456, 0.20701966780270625),
 (4657, 0.20701966780270625),
 (4966, 0.20701966780270625),
 (6192, 0.20701966780270625),
 (1750, 0.20619652471058064),
 (3045, 0.20619652471058064),
 (4659, 0.20619652471058064),
 (151, 0.20573779994945587),
 (788, 0.20573779994945587),
 (1384, 0.20573779994945587),
 (1633, 0.20573779994945587),
 (5501, 0.20573779994945587),
 (5598, 0.20573779994945587),
 (1030, 0.20475708983698054),
 (2416, 0.20475708983698054),
 (6058, 0.20475708983698054),
 (444, 0.20475708983698052),
 (2333, 0.20437977982832195),
 (4737, 0.20437977982832195),
 (214, 0.2043353446109627),
 (433, 0.2043353446109627),
 (870, 0.2041241452319315),
 (1805, 0.20367270904666504),
 (2038, 0.20293851577273642),
 (611, 0.2029385157727364),
 (882, 0.2029385157727364),
 (5819, 0.20287055622991232),
 (2054, 0.20261022461827694),
 (3295, 0.20261022461827694),
 (2508, 0.20256711147285467),
 (3492, 0.20256711147285467),
 (4467, 0.20256711147285467),
 (6020, 0.20256711147285467),
 (6480, 0.2020305089104422),
 (2261, 0.20143682408616567),
 (4402, 0.20143682408616567),
 (5560, 0.20143682408616567),
 (2167, 0.200885850922577),
 (3952, 0.20083857810137354),
 (1092, 0.20059435495071948),
 (1053, 0.2005738892714385),
 (1175, 0.2005738892714385),
 (386, 0.20057388927143846),
 (6099, 0.20057388927143846),
 (4311, 0.20025046972870356),
 (2208, 0.1996674976919165),
 (1657, 0.19959884332214914),
 (2429, 0.19920476822239896),
 (5768, 0.19920476822239894),
 (1953, 0.19851666679418606),
 (2685, 0.19851666679418603),
 (5325, 0.19847104650936118),
 (1559, 0.19839002137983244),
 (2132, 0.19839002137983244),
 (285, 0.1976664844429603),
 (2176, 0.1976664844429603),
 (5442, 0.19756519492339994),
 (1544, 0.1975651949233999),
 (2236, 0.1973855084879307),
 (3450, 0.1973855084879307),
 (5207, 0.1973855084879307),
 (4491, 0.1973114009168982),
 (1221, 0.19720265943665385),
 (1470, 0.19720265943665385),
 (3759, 0.19720265943665385),
 (673, 0.19639610121239315),
 (1186, 0.19639610121239315),
 (3400, 0.19639610121239315),
 (4803, 0.19639610121239315),
 (5774, 0.19639610121239315),
 (4064, 0.19627346860523626),
 (1481, 0.19599157740244455),
 (585, 0.19596545041740515),
 (827, 0.19596545041740515),
 (848, 0.19596545041740515),
 (4014, 0.1955795646794894),
 (27, 0.19518001458970666),
 (3456, 0.19518001458970666),
 (5045, 0.19518001458970666),
 (5516, 0.19518001458970666),
 (6214, 0.19518001458970666),
 (6242, 0.19518001458970666),
 (776, 0.19518001458970663),
 (260, 0.19469788948631686),
 (1931, 0.19469788948631686),
 (740, 0.1944611170656493),
 (5396, 0.1944611170656493),
 (5494, 0.1944611170656493),
 (5271, 0.19440394783993478),
 (242, 0.19440394783993475),
 (280, 0.19440394783993475),
 (1069, 0.19440394783993475),
 (5350, 0.19440394783993475),
 (2767, 0.19399589841579268),
 (703, 0.19399589841579265),
 (4567, 0.19399589841579265),
 (2558, 0.19399589841579262),
 (3405, 0.19399589841579262),
 (4400, 0.19342948582466574),
 (6417, 0.19342948582466574),
 (99, 0.1930468356263361),
 (2488, 0.1930468356263361),
 (5388, 0.1930468356263361),
 (486, 0.19304683562633607),
 (4294, 0.19304683562633607),
 (1702, 0.1928791874526149),
 (3639, 0.1928791874526149),
 (5820, 0.1928791874526149),
 (1860, 0.19278507708475195),
 (3868, 0.19278507708475195),
 (3970, 0.19278507708475195),
 (4921, 0.19278507708475195),
 (6488, 0.19278507708475195),
 (356, 0.19278507708475193),
 (2988, 0.19258222162991087),
 (452, 0.19258222162991084),
 (949, 0.19258222162991084),
 (4710, 0.19258222162991084),
 (4429, 0.1921345458387807),
 (5356, 0.1921345458387807),
 (68, 0.19138975058773822),
 (1050, 0.19094065395649332),
 (1325, 0.19094065395649332),
 (1713, 0.19094065395649332),
 (1871, 0.19094065395649332),
 (2747, 0.19094065395649332),
 (5825, 0.19094065395649332),
 (362, 0.19075675652968382),
 (6299, 0.19075675652968382),
 (5853, 0.1907567565296838),
 (6447, 0.1907567565296838),
 (971, 0.1904761904761905),
 (3052, 0.1904761904761905),
 (5986, 0.1904761904761905),
 (2790, 0.18993429409939658),
 (998, 0.18898223650461363),
 (2557, 0.18898223650461363),
 (4018, 0.18898223650461363),
 (2530, 0.1889822365046136),
 (2826, 0.1889822365046136),
 (4120, 0.1889822365046136),
 (4856, 0.1882483221340047),
 (5574, 0.1882483221340047),
 (5667, 0.1882483221340047),
 (5872, 0.1882483221340047),
 (5268, 0.18802535827258876),
 (1744, 0.18802535827258873),
 (3102, 0.18802535827258873),
 (5493, 0.18802535827258873),
 (6335, 0.18802535827258873),
 (1595, 0.1872563351797078),
 (1641, 0.1872563351797078),
 (3310, 0.1872563351797078),
 (3677, 0.1872563351797078),
 (4691, 0.1872563351797078),
 (5358, 0.18712029714127995),
 (43, 0.18609684207969418),
 (1596, 0.18609684207969418),
 (1616, 0.18609684207969418),
 (1969, 0.18609684207969418),
 (2093, 0.18609684207969418),
 (4366, 0.18609684207969418),
 (4535, 0.18609684207969418),
 (4631, 0.18609684207969418),
 (6476, 0.18609684207969418),
 (1314, 0.18575940419178427),
 (1364, 0.18575940419178427),
 (1680, 0.18575940419178427),
 (2012, 0.18575940419178427),
 (1665, 0.18557687223952257),
 (4959, 0.18557687223952257),
 (4123, 0.1852396434087371),
 (308, 0.18523964340873708),
 (4673, 0.18523964340873708),
 (921, 0.18519463316790533),
 (1584, 0.18516401995451032),
 (3927, 0.18516401995451032),
 (3928, 0.18516401995451032),
 (4782, 0.18516401995451032),
 (6330, 0.18516401995451032),
 (5956, 0.1851640199545103),
 (469, 0.18442777839082938),
 (1759, 0.18442777839082938),
 (3330, 0.18442777839082938),
 (351, 0.18401748249129446),
 (3711, 0.18401748249129446),
 (5175, 0.18401748249129446),
 (6398, 0.18401748249129446),
 (160, 0.18394180184548975),
 (245, 0.18394180184548975),
 (1935, 0.18394180184548975),
 (6421, 0.18394180184548975),
 (4823, 0.18302853955092346),
 (3421, 0.1825741858350554),
 (3491, 0.1825741858350554),
 (1226, 0.18257418583505539),
 (1317, 0.18257418583505539),
 (3755, 0.18257418583505539),
 (5338, 0.18257418583505539),
 (624, 0.18257418583505536),
 (4809, 0.18257418583505536),
 (4893, 0.18257418583505536),
 (5669, 0.18257418583505536),
 (5480, 0.18234920215644923),
 (845, 0.18200630207731602),
 (1335, 0.18200630207731602),
 (4276, 0.18200630207731602),
 (5968, 0.18200630207731602),
 (1630, 0.18184824186332704),
 (300, 0.18184824186332701),
 (5873, 0.18184824186332701),
 (789, 0.18156825980064073),
 (1924, 0.18156825980064073),
 (2225, 0.18156825980064073),
 (2745, 0.18156825980064073),
 (5919, 0.18156825980064073),
 (3545, 0.18079726583031927),
 (1736, 0.18059841095769247),
 (2109, 0.18059841095769247),
 (2943, 0.18059841095769247),
 (244, 0.18005965464253748),
 (258, 0.18005965464253748),
 (451, 0.18005965464253748),
 (1099, 0.18005965464253748),
 (2073, 0.18005965464253748),
 (6273, 0.18005965464253748),
 (6375, 0.18005965464253748),
 (510, 0.1800205749557739),
 (564, 0.1800205749557739),
 (1427, 0.1800205749557739),
 (1984, 0.1800205749557739),
 (3347, 0.1800205749557739),
 (3947, 0.1800205749557739),
 (4717, 0.17991734622146657),
 (1240, 0.17928429140015906),
 (1574, 0.17928429140015906),
 (2885, 0.17928429140015906),
 (4171, 0.17928429140015906),
 (5499, 0.17928429140015906),
 (1798, 0.17928429140015903),
 (77, 0.17817416127494964),
 (104, 0.17817416127494962),
 (133, 0.17817416127494962),
 (1059, 0.17817416127494962),
 (1269, 0.17817416127494962),
 (2380, 0.17817416127494962),
 (3187, 0.17817416127494962),
 (4833, 0.17817416127494962),
 (878, 0.1781741612749496),
 (2552, 0.1781741612749496),
 (3580, 0.1781741612749496),
 (4985, 0.1781741612749496),
 (6077, 0.1781741612749496),
 (605, 0.17757120130114437),
 (1282, 0.17757120130114437),
 (3483, 0.17757120130114437),
 (3537, 0.17757120130114437),
 (4077, 0.17757120130114437),
 (5102, 0.17757120130114437),
 (3526, 0.17757120130114434),
 (3798, 0.17757120130114434),
 (4807, 0.17757120130114434),
 (46, 0.17699808135119716),
 (2342, 0.17699808135119716),
 (2641, 0.17699808135119716),
 (4346, 0.17699808135119716),
 (5043, 0.17699808135119716),
 (5134, 0.17699808135119716),
 (5612, 0.17699808135119716),
 (6100, 0.17699808135119716),
 (5643, 0.17699808135119713),
 (3930, 0.1769595993241414),
 (1763, 0.1765469659009499),
 (213, 0.17636890537566463),
 (3432, 0.17636890537566463),
 (299, 0.17634668567096218),
 (5347, 0.17634668567096218),
 (4128, 0.1760056322703504),
 (5437, 0.17584498711333246),
 (117, 0.17521916101261562),
 (813, 0.17521916101261562),
 (2653, 0.17521916101261562),
 (2681, 0.17521916101261562),
 (3635, 0.17521916101261562),
 (3864, 0.17521916101261562),
 (5107, 0.17521916101261562),
 (5124, 0.17521916101261562),
 (5706, 0.17521916101261562),
 (5957, 0.17521916101261562),
 (2428, 0.1749635530559413),
 (3655, 0.1749635530559413),
 (259, 0.17496355305594127),
 (2827, 0.17496355305594127),
 (4103, 0.17496355305594127),
 (5188, 0.17496355305594127),
 (5337, 0.17496355305594127),
 (6198, 0.17496355305594127),
 (1144, 0.1745743121887939),
 (4371, 0.1745743121887939),
 (6298, 0.1745743121887939),
 (1896, 0.17359126870735342),
 (1060, 0.1735912687073534),
 (1679, 0.1735912687073534),
 (4813, 0.1735912687073534),
 (5121, 0.1735912687073534),
 (485, 0.17359126870735336),
 (253, 0.17295817388759027),
 (838, 0.17295817388759027),
 (997, 0.17295817388759027),
 (2014, 0.17295817388759027),
 (2043, 0.17295817388759027),
 (2658, 0.17295817388759027),
 (3749, 0.17295817388759027),
 (4334, 0.17295817388759027),
 (4843, 0.17295817388759027),
 (6263, 0.17295817388759027),
 (75, 0.17285432628057715),
 (1347, 0.17285432628057715),
 (2290, 0.17285432628057715),
 (4189, 0.17285432628057715),
 (5199, 0.17285432628057715),
 (1058, 0.17251638983558856),
 (1604, 0.17251638983558856),
 (2203, 0.17251638983558856),
 (2668, 0.17251638983558856),
 (4350, 0.17251638983558856),
 (2351, 0.17251638983558854),
 (1565, 0.1722507755289644),
 (5265, 0.1722507755289644),
 (319, 0.17192047651837583),
 (496, 0.17192047651837583),
 (2771, 0.17192047651837583),
 (3621, 0.17192047651837583),
 (3773, 0.17192047651837583),
 (3849, 0.17192047651837583),
 (5344, 0.17192047651837583),
 (5580, 0.17192047651837583),
 (6436, 0.17192047651837583),
 (100, 0.17144816662454657),
 (4049, 0.17144816662454657),
 (2352, 0.17118419700436519),
 (2691, 0.17118419700436519),
 (3447, 0.17118419700436519),
 (4112, 0.17118419700436519),
 (5035, 0.17118419700436519),
 (5648, 0.17118419700436519),
 (5722, 0.17118419700436519),
 (98, 0.17078251276599332),
 (2173, 0.17078251276599332),
 (4347, 0.1707572546851385),
 (2869, 0.16966039074466752),
 (4131, 0.16966039074466752),
 (5837, 0.16966039074466752),
 (6470, 0.16966039074466752),
 (503, 0.16956156135971895),
 (1179, 0.16956156135971895),
 (2303, 0.16956156135971895),
 (1010, 0.1690308509457033),
 (1770, 0.1690308509457033),
 (2107, 0.1690308509457033),
 (2260, 0.1690308509457033),
 (2358, 0.1690308509457033),
 (2582, 0.1690308509457033),
 (2702, 0.1690308509457033),
 (2894, 0.1690308509457033),
 (3197, 0.1690308509457033),
 (4213, 0.1690308509457033),
 (4601, 0.1690308509457033),
 (5690, 0.1690308509457033),
 (6042, 0.1690308509457033),
 (78, 0.16868694244915797),
 (372, 0.16868694244915797),
 (418, 0.16868694244915797),
 (747, 0.16868694244915797),
 (1677, 0.16868694244915797),
 (2298, 0.16868694244915797),
 (2453, 0.16868694244915797),
 (688, 0.16868694244915794),
 (4973, 0.16868694244915794),
 (5425, 0.16868694244915794),
 (6220, 0.16868694244915794),
 (621, 0.16840826742715195),
 (3991, 0.16840826742715195),
 (1172, 0.1683587574253685),
 (1474, 0.1683587574253685),
 (1674, 0.1683587574253685),
 (1720, 0.1683587574253685),
 (1863, 0.1683587574253685),
 (2205, 0.1683587574253685),
 (5596, 0.1683587574253685),
 (455, 0.16835875742536846),
 (233, 0.1679842102263232),
 (2817, 0.1679842102263232),
 (3300, 0.1679842102263232),
 (5662, 0.1679842102263232),
 (4925, 0.16747497831617858),
 (1338, 0.16736548175114463),
 (1753, 0.16718346377260584),
 (420, 0.16666666666666669),
 (3701, 0.16666666666666669),
 (5048, 0.16666666666666669),

In [627]:
recommend("damsel")

The Dark Kingdom
Dragonslayer
Raya and the Last Dragon
How to Train Your Dragon 2
Charming

In [622]:
import pickle

In [623]:
pickle.dump(similarity, open('model/similarity.pkl' , 'wb'))